### ISSUE TITLE
HTML5 Video element should know the bitrate switch due to MSE

### ISSUE THREAD

**Issue by ghost** [w3c/html-extension#25]
Currently the video element in HTML5 is built for progressive playback. With the MSE enabled ability to switch video streams on the fly, the bitrate switch should be available to end users. A specific use case is of video/network quality monitoring.

This request probably spans multiple w3c standards.

**Comment by chaals** [comment]
This issue should be raised on e.g. the [HTML specification itself](https://github.com/w3c/html) rather than here.

This repository is for a simple list of specifications (including) MSE that extend HTML, and is not the place to propose any changes to specifications.
